In [1]:
import pandas as pd

# Loading dataset

In [2]:
data  = pd.read_csv("https://raw.githubusercontent.com/dataprofessor/data/master/delaney_solubility_with_descriptors.csv")

In [3]:
data

MolLogP    MolWt  NumRotatableBonds  AromaticProportion   logS
0     2.59540  167.850                0.0            0.000000 -2.180
1     2.37650  133.405                0.0            0.000000 -2.000
2     2.59380  167.850                1.0            0.000000 -1.740
3     2.02890  133.405                1.0            0.000000 -1.480
4     2.91890  187.375                1.0            0.000000 -3.040
...       ...      ...                ...                 ...    ...
1139  1.98820  287.343                8.0            0.000000  1.144
1140  3.42130  286.114                2.0            0.333333 -4.925
1141  3.60960  308.333                4.0            0.695652 -3.893
1142  2.56214  354.815                3.0            0.521739 -3.790
1143  2.02164  179.219                1.0            0.461538 -2.581

[1144 rows x 5 columns]

## splitting training and test dataset

In [4]:
X = data.drop('logS',axis=1)

In [5]:
Y = data['logS']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train , x_test , y_train , y_test = train_test_split(X , Y , test_size=0.2 , random_state=100)

In [8]:
## Standardize the dataset
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [9]:
x_train=scaler.fit_transform(x_train)


In [10]:
x_test=scaler.transform(x_test)


In [11]:
x_train

array([[ 0.37493869, -0.89775655,  1.03224993, -1.04540513],
       [-2.46740661, -0.60446519, -0.81972789, -1.04540513],
       [-1.59575332, -0.34823067, -0.81972789, -1.04540513],
       ...,
       [ 1.8013319 ,  0.51822357, -0.81972789,  1.57823088],
       [ 0.78692171, -0.16955813,  2.88422775, -1.04540513],
       [ 0.03772014,  1.04822879,  0.2914588 , -0.17085979]])

In [12]:
x_test

array([[ 2.48208190e-01, -3.07794303e-01,  1.77304106e+00,
        -1.04540513e+00],
       [ 2.62386078e+00,  1.54518543e+00, -4.49332323e-01,
         8.98028953e-01],
       [-2.79617831e-01, -5.74098616e-01, -8.19727887e-01,
         1.60473226e+00],
       [-2.54576580e-01, -8.27395701e-01, -8.19727887e-01,
        -1.04540513e+00],
       [-4.10148074e-01, -9.37799946e-01, -8.19727887e-01,
         1.14095821e+00],
       [-1.37125306e+00, -6.72645064e-01, -8.19727887e-01,
         1.57823088e+00],
       [-1.01185667e+00, -1.42959889e+00, -4.49332323e-01,
        -1.04540513e+00],
       [-2.23000466e+00,  8.12281223e-01,  6.61854368e-01,
        -1.70859792e-01],
       [ 1.55677687e+00,  5.30002777e-01, -4.49332323e-01,
         1.28671577e+00],
       [ 5.07766200e-01,  2.82236711e-01, -7.89367595e-02,
        -1.65282618e-02],
       [ 6.16205704e-01, -3.47808228e-01, -8.19727887e-01,
         1.86974599e+00],
       [-2.66335081e-01, -8.79306720e-01, -8.19727887e-01,
      

### importing linear regression model

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
# training the model 

In [15]:
lr_model = LinearRegression()

In [16]:
lr_model.fit(x_train , y_train)

LinearRegression()

In [17]:
# apply the model to make prediction 

In [18]:
train_pred = lr_model.predict(x_train)
test_pred  = lr_model.predict(x_test)

In [19]:
len(train_pred)

915

In [20]:
len(test_pred)

229

# Evaluating the prediction

In [21]:

from sklearn.metrics import mean_squared_error, r2_score

lr_train_mse = mean_squared_error(y_train,train_pred)
lr_train_r2 = r2_score(y_train, train_pred)

lr_test_mse = mean_squared_error(y_test,test_pred)
lr_test_r2 = r2_score(y_test,test_pred)
     

In [22]:

print('LR MSE (Train): ', lr_train_mse)
print('LR R2 (Train): ', lr_train_r2)
print('LR MSE (Test): ', lr_test_mse)
print('LR R2 (Test): ', lr_test_r2)

LR MSE (Train):  1.007536295109369
LR R2 (Train):  0.7645051774663391
LR MSE (Test):  1.0206953660861033
LR R2 (Test):  0.7891616188563282


In [23]:
import pickle

In [24]:
pickle.dump(scaler,open('scaler.pkl','wb'))


In [25]:
pickle.dump(lr_model,open('regmodel.pkl','wb'))


In [26]:
pickled_model=pickle.load(open('regmodel.pkl','rb'))


In [27]:
test_data = ([[2.91000,172.268,7.0,0.000000]])


In [28]:
import numpy as np



# Assuming 'scaler' is your scaler object
# Apply scaling to the test data
test_data_array_scaled = scaler.transform(test_data)

# Reshape the array
test_data_reshaped = test_data_array_scaled.reshape(1, -1)

# Make predictions
predictions = pickled_model.predict(test_data_array_scaled)


c:\Users\yethu.krishnan\repos\ML_PROJECT\venv\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [29]:
predictions

array([-3.0572287])

In [30]:
test_data_array_scaled.shape

(1, 4)

In [32]:
test_data_reshaped.shape

(1, 4)